apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-server
commonLabels:
  app: jellyfin
  project: media-server
commonAnnotations:
  website: https://jellyfin.org
  Dockerfile: https://github.com/linuxserver/docker-jellyfin
resources:
- ingress.yaml
- statefulset.yaml
- service.yaml