apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.ui_port }}
      targetPort: {{ .Values.ui_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "media-server.selectorLabels" . | nindent 4 }}
